In [2]:
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [25]:
data = pd.read_csv('affair_data.csv')

In [26]:
y = data['affair']

In [27]:
X = data
del X['affair']

In [28]:
X = pd.get_dummies(X, columns=['occupation', 'occupation_husb', 'religious'])

In [29]:
from sklearn.feature_selection import SelectKBest, chi2, f_classif

In [30]:
selector = SelectKBest(f_classif, k=5)

In [32]:
result = selector.fit(X, y)

In [34]:
result.get_support(indices=True)

array([ 0,  1,  2,  3, 20])

In [39]:
X.loc[:, result.get_support()].head(5)

rate_marriage  age  yrs_married  children  religious_4.0
0              3   32          9.0         3              0
1              3   27         13.0         3              0
2              4   22          2.5         0              0
3              4   37         16.5         4              0
4              5   27          9.0         1              0

In [41]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [42]:
selector_rfe = RFE(LogisticRegression(), n_features_to_select=5)

In [43]:
result_rfe = selector_rfe.fit(X, y)

In [44]:
result_rfe.get_support(indices=True)

array([ 0,  5,  9, 13, 20])

In [45]:
X.loc[:, result_rfe.get_support()].head(5)

rate_marriage  occupation_1.0  occupation_5.0  occupation_husb_3.0  \
0              3               0               0                    0   
1              3               0               0                    0   
2              4               0               0                    0   
3              4               0               1                    0   
4              5               0               0                    0   

   religious_4.0  
0              0  
1              0  
2              0  
3              0  
4              0

In [46]:
from sklearn.feature_selection import RFECV
from sklearn.cross_validation import StratifiedKFold

In [47]:
CV = StratifiedKFold(y, n_folds=10, random_state=0)

In [54]:
my_selector = RFECV(LogisticRegression(), cv=CV, scoring='roc_auc')

In [55]:
my_selector.fit(X, y)

RFECV(cv=sklearn.cross_validation.StratifiedKFold(labels=[1 1 ..., 0 0], n_folds=10, shuffle=False, random_state=0),
   estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
   estimator_params=None, scoring='roc_auc', step=1, verbose=0)

In [50]:
my_selector.get_support(indices=True)

array([ 0,  1,  2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [51]:
X.loc[:, my_selector.get_support()].head(5)

rate_marriage  age  yrs_married  occupation_1.0  occupation_2.0  \
0              3   32          9.0               0               1   
1              3   27         13.0               0               0   
2              4   22          2.5               0               0   
3              4   37         16.5               0               0   
4              5   27          9.0               0               0   

   occupation_3.0  occupation_4.0  occupation_5.0  occupation_6.0  \
0               0               0               0               0   
1               1               0               0               0   
2               1               0               0               0   
3               0               0               1               0   
4               1               0               0               0   

   occupation_husb_1.0  occupation_husb_2.0  occupation_husb_3.0  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   occupation_husb_4.0  occupation_husb_5.0  occupation_husb_6.0  \
0                    0                    1                    0   
1                    1                    0                    0   
2                    0                    1                    0   
3                    0                    1                    0   
4                    1                    0                    0   

   religious_1.0  religious_2.0  religious_3.0  religious_4.0  
0              0              0              1              0  
1              1              0              0              0  
2              1              0              0              0  
3              0              0              1              0  
4              1              0              0              0